// 定义各种常量
export const ADD_NUMBER = 'ADD_NUMBER';

export const ADD_ONE = 'ADD_ONE';

export const CHANGE_BANNERS = 'CHANGE_BANNERS';
export const CHANGE_RECOMMEND = 'CHANGE_RECOMMEND';

export const FETCH_LUNBO_MULTIDASTAT = 'FETCH_LUNBO_MULTIDASTAT';